### ISSUE TITLE
pretty_print doesn't work as expected

### ISSUE THREAD

**Issue by ekampp** [savonrb/gyoku#63]
Hi there. 

I wanted to generate some XML, and I wanted it to look nice. Having to concatenate some identical tags I set `unwrap: true` (which works fine), but the result wasn't prettified.

``` ruby
pry(main)> Gyoku.xml({ a: :b, c: [{ d: :e }, { f: :g }] }, { unwrap: true })
=> "<a>b</a><c><d>e</d><f>g</f></c>"

pry(main)> Gyoku.xml({ a: :b, c: [{ d: :e }, { f: :g }] }, { unwrap: true, pretty_print: true  })
=> "<a>b</a><c><d>e</d><f>g</f></c>"

pry(main)> Gyoku.xml({ a: :b, c: [{ d: :e }, { f: :g }] }, { unwrap: true, pretty_print: true, compact: false })
=> "<a>b</a><c><d>e</d><f>g</f></c>"
```

I would have expected both of the last results to be something like this:

``` xml
<a>b</a>
<c>
  <d>e</d>
  <f>g</f>
</c>
```

I'm currently running Gyoku v. 1.3.1

Thanks in advance

**Comment by Sharagoz** [comment]
V1.3.1 doesnt seem to include this feature. You can get the feature by grabbing the gem from master though:
Update your gemfile like so:
`gem 'gyoku', git: 'git@github.com:savonrb/gyoku.git', ref: '954d002'`

**Comment by MaxFedotov** [comment]
Hello @bjorntrondsen. And is it possible to create a new release with this feature and publish it to rubygems? Thanks a lot in advance :)

**Comment by bjorntrondsen** [comment]
@MaxFedotov Im just a passer by but maybe @tjarratt can help :)

**Comment by MaxFedotov** [comment]
@bjorntrondsen Oh, sorry :)
@tjarratt Is it possible to create a new release with this feature and publish it to rubygems? Thanks a lot in advance :)

**Comment by anirbanmu** [comment]
I've run into this too just now.

@tjarratt a release of latest master to rubygems would be really appreciated if you have the time. Thanks in advance.

**Comment by RulerOf** [comment]
Requesting the same a couple years later :)

**Comment by olleolleolle** [comment]
Closing this issue, now that #80 v1.4.0 has been released.
