### ISSUE TITLE
Circular Require detected by JRuby-9+

### ISSUE THREAD

**Issue by skoona** [savonrb/gyoku#68]
Line <gem>/lib/gyoku/array.rb:3  require "gyoku/hash"

establishes a circular require pattern.  Commenting that line out seems to resolve the issue.  The following is the full exception listing from JRuby-9.1.14.0

`/Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247: warning: loading in progress, circular require considered harmful - /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/gyoku-1.3.1/lib/gyoku/hash.rb
                   require at org/jruby/RubyKernel.java:955
          block in require at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
           load_dependency at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:232
                   require at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
                    <main> at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/gyoku-1.3.1/lib/gyoku/array.rb:3
                   require at org/jruby/RubyKernel.java:955
           block in (root) at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:1
                   require at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
           load_dependency at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:232
                    <main> at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
                   require at org/jruby/RubyKernel.java:955
           block in (root) at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/gyoku-1.3.1/lib/gyoku/hash.rb:3
                    (root) at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:1
                   require at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
                    <main> at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:232
                   require at org/jruby/RubyKernel.java:955
          block in require at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
                    (root) at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/gyoku-1.3.1/lib/gyoku.rb:2
                    (root) at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:1
                    <main> at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
                   require at org/jruby/RubyKernel.java:955
  block in load_dependency at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:232
                   require at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
                    (root) at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/akami-1.3.1/lib/akami/wsse.rb:7
                    <main> at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:1
                   require at org/jruby/RubyKernel.java:955
          block in require at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
           load_dependency at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:232
                   require at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
                    <main> at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/akami-1.3.1/lib/akami.rb:2
                   require at org/jruby/RubyKernel.java:955
           block in (root) at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:1
                   require at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
           load_dependency at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:232
                    <main> at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
                   require at org/jruby/RubyKernel.java:955
           block in (root) at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/savon-2.11.1/lib/savon/header.rb:1
                    (root) at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:1
                   require at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
                    <main> at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:232
                   require at org/jruby/RubyKernel.java:955
          block in require at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
                    (root) at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/savon-2.11.1/lib/savon/builder.rb:1
                    (root) at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:1
                    <main> at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
                   require at org/jruby/RubyKernel.java:955
  block in load_dependency at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:232
                   require at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
                    (root) at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/savon-2.11.1/lib/savon/operation.rb:4
                    <main> at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:1
                   require at org/jruby/RubyKernel.java:955
          block in require at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
                      each at org/jruby/RubyArray.java:1734
  block in load_dependency at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:232
                      each at org/jruby/RubyArray.java:1734
                   require at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
                    (root) at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/savon-2.11.1/lib/savon/client.rb:1
                    <main> at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:1
                   require at org/jruby/RubyKernel.java:955
          block in require at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
                       tap at org/jruby/RubyKernel.java:1741
           load_dependency at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:232
                   require at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/activesupport-4.1.16/lib/active_support/dependencies.rb:247
                    <main> at /Users/jscott/rDeveloper/BMIService/vendor/bundle/jruby/2.3.0/gems/savon-2.11.1/lib/savon.rb:27
                   require at org/jruby/RubyKernel.java:955
                    <main> at /Users/jscott/.rvm/gems/jruby-9.1.14.0@bmiservice/gems/bundler-1.16.0/lib/bundler/runtime.rb:1`

**Comment by olleolleolle** [comment]
@skoona Thanks for the report and analysis! #69 was merged, and this makes me confident in closing this Issue. 🎉
