### ISSUE TITLE
Rexml is required but is not in the Gemfile

### ISSUE THREAD

**Issue by bakku** [savonrb/gyoku#70]
Since this gem hasn't been released in a while the only possible way to use the pretty printing is to do this:

Gemfile:

```
source 'https://rubygems.org'

gem 'gyoku', git: 'https://github.com/savonrb/gyoku'
```

script.rb:

```
require 'bundler/setup'
require 'gyoku'

xml = Gyoku.xml({ document: "xy" }, { pretty_print: true })
```

This fails however since `rexml` is used for pretty printing, so the Gemfile must look like this to make the pretty printing work:

```
source 'https://rubygems.org'

gem 'gyoku', git: 'https://github.com/savonrb/gyoku'
gem 'rexml'
```

`rexml` should be included in the Gemfile of `gyoku`. It should not be necessary for the user of the library to include it in his/her Gemfile.

**Comment by olleolleolle** [comment]
Can you try now, @bakku, if this works, I merged a change.

**Comment by bakku** [comment]
Works great! Didn't know it was related to Ruby 3 ... now I see why it was not a dependency of gyoku.. What about creating a new release so features such as these could be used without loading the library directly from github?

**Comment by olleolleolle** [comment]
Excellent, then this issue can be closed. Thanks for verifying.
